library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by Schematic Studio  (target: Xilinx Spartan-7 / Vivado)
-- Schematic: mux_4to1_8bit

entity mux_4to1_8bit is
  Port (
    data0 : in  STD_LOGIC_VECTOR(7 downto 0);
    data1 : in  STD_LOGIC_VECTOR(7 downto 0);
    data2 : in  STD_LOGIC_VECTOR(7 downto 0);
    data3 : in  STD_LOGIC_VECTOR(7 downto 0);
    sel0 : in  STD_LOGIC;
    sel1 : in  STD_LOGIC;
    result : out STD_LOGIC_VECTOR(7 downto 0)
  );
end mux_4to1_8bit;

architecture Behavioral of mux_4to1_8bit is
  signal n1_y : STD_LOGIC_VECTOR(7 downto 0);
begin

  -- combinational logic
  n1_y <= data0 when (sel1 = '0' and sel0 = '0') else
             data1 when (sel1 = '0' and sel0 = '1') else
             data2 when (sel1 = '1' and sel0 = '0') else
             data3 when (sel1 = '1' and sel0 = '1') else (others => '0');

  -- output drivers
  result <= n1_y;

end Behavioral;
